### ISSUE TITLE
name configuration

### ISSUE THREAD

**Issue by RATCHAW** [flexbase-eng/vite-plugin-runtime#5]
When I change the name configuration to `'config'`, `config.d.ts` gets generated. 
` import.meta.config.foo` does not work even though the types refer to it. To make it work, I have to use `import.meta.env.foo`, which has no types.
 
 My config file:
 
```ts
import * as path from "path";
import react from "@vitejs/plugin-react-swc";
import svgr from "vite-plugin-svgr";
import { runtimeEnv, runtimeHtml } from "vite-plugin-runtime";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [react(), svgr(), runtimeEnv(), runtimeHtml()],
  runtimeEnv: {
    generateTypes: true,
    generatedTypesPath: () => "./src",
    injectHtml: true,
    name: "config",
  },
  build: {
    outDir: "build",
  },
  assetsInclude: ["**/*.svg"],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
```

**Comment by robert-dean** [comment]
I tried this on one of our internal projects and it worked fine. I think the issue you're running into is instead of using `import.meta.config.*` use `window.config.*`
